# Generated by Django 6.0.6 on 2026-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_auth_provider_user_provider_id'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.ManyToManyField(blank=True, db_table='user_skills', related_name='job_seekers', to='skills.skill'),
        ),
    ]
