# Generated by Django 6.0.6 on 2026-07-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('observability', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestlog',
            name='response_body',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestlog',
            name='response_headers',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
