# Generated by Django 6.0.6 on 2026-08-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(blank=True, db_table='job_skills', related_name='jobs', to='skills.skill'),
        ),
    ]
