# Generated by Django 6.0.6 on 2026-07-28 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0003_company_registration_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='companymember',
            name='role',
            field=models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='member', max_length=10),
        ),
    ]
