# Generated by Django 6.0.6 on 2026-09-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('companies', '0004_companymember_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
